<?php
    define('ERR_LOGIN_NOTFOUND', 10);
	
    define('ERR_REGISTER_INTEGRITYCHECK_FAILED', 20);
    define('ERR_REGISTER_USERNAME_NOTPROVIDED', 21);
    define('ERR_REGISTER_NAME_NOTPROVIDED', 22);
    define('ERR_REGISTER_PASSWORD_NOTPROVIDED', 23);
    define('ERR_REGISTER_EMAIL_NOTPROVIDED', 24);
    define('ERR_REGISTER_USERNAME_TOOLONG', 25);
    define('ERR_REGISTER_NAME_TOOLONG', 26);
    define('ERR_REGISTER_EMAIL_INUSE', 27);
    define('ERR_REGISTER_EMAIL_NOTVALID', 28);
	
    define('ERR_PROBLEM_ID_NOTPROVIDED', 30);
    define('ERR_PROBLEM_NOTFOUND', 31);
    define('ERR_PROBLEM_SOLUTION_NOTFOUND', 32);
    define('ERR_PROBLEM_SOLUTION_MISMATCH', 33);
    define('ERR_PROBLEM_SOLUTION_ID_NOTPROVIDED', 34);
    define('ERR_PROBLEM_SOLUTION_UPLOAD_INVALID_PARAM', 35);
    define('ERR_PROBLEM_SOLUTION_UPLOAD_NOFILE', 36);
    define('ERR_PROBLEM_SOLUTION_UPLOAD_SIZE_EXCEEDED', 37);
    define('ERR_PROBLEM_SOLUTION_UPLOAD_UNKNOWN_ERR', 38);
    define('ERR_PROBLEM_SOLUTION_UPLOAD_LANGUAGE_NOTSET', 39);
	
    
	define('ERR_PAGE_NOTFOUND', 40);
	
	define('ERR_PERMISSION_NOTAUTH', 50);
	
	define('ERR_PROBLEM_SOLUTION_USER_NOTFOUND', 60);
	
	define('ERR_NEWPROBLEM_NAME_NOTPROVIDED', 70);
	define('ERR_NEWPROBLEM_NAME_CLEAN_NOTPROVIDED', 71);
	define('ERR_NEWPROBLEM_AUTHOR_NOTPROVIDED', 72);
	define('ERR_NEWPROBLEM_NAME_TOOLONG', 73);
	define('ERR_NEWPROBLEM_NAME_CLEAN_TOOLONG', 74);
	define('ERR_NEWPROBLEM_NAME_CLEAN_NOTVALID', 75);
	define('ERR_NEWPROBLEM_AUTHOR_TOOLONG', 76);
	define('ERR_NEWPROBLEM_INTEGRITYCHECK_FAILED', 77);

	define('ERR_NEWCLASS_INTEGRITYCHECK_FAILED', 80);
	define('ERR_NEWCLASS_NAME_NOTPROVIDED', 81);
	define('ERR_NEWCLASS_NAME_TOOLONG', 82);

	define('ERR_JOINCLASS_INTEGRITYCHECK_FAILED', 90);
	define('ERR_JOINCLASS_ACCESSKEY_NOTPROVIDED', 91);
	define('ERR_JOINCLASS_ACCESSKEY_NOTVALID', 92);
	define('ERR_JOINCLASS_KEY_NOTEXISTS', 93);

	define('ERR_CLASS_ID_NOTPROVIDED', 100);
	define('ERR_CLASS_NEWHOMEWORK_INTEGRITYCHECK_FAILED', 101);
	define('ERR_CLASS_NEWHOMEWORK_NAME_NOTPROVIDED', 102);
	define('ERR_CLASS_NEWHOMEWORK_NAME_TOOLONG', 103);
	define('ERR_CLASS_NEWHOMEWORK_DATE_NOTPROVIDED', 104);